export const db = [{mynd: 'rocket', svar: 'eldflaug'},
					{mynd: 'automobile', svar: 'bíll'},
					{mynd: 'bicycle', svar: 'reiðhjól'},
					{mynd: 'circle', svar: 'hringur'},
					{mynd: 'female', svar: 'kona'},
					{mynd: 'flag', svar: 'fáni'},
					{mynd: 'home', svar: 'heimili'},
					{mynd: 'heart', svar: 'hjarta'},
					{mynd: 'plane', svar: 'flugvél'},
					{mynd: 'shower', svar: 'sturta'},
					{mynd: 'phone', svar: 'sími'},
					{mynd: 'ship', svar: 'skip'},
					{mynd: 'smile-o', svar: 'bros'},
					{mynd: 'soccer-ball-o', svar: 'fótbolti'},
					{mynd: 'tree', svar: 'tré'},
					{mynd: 'truck', svar: 'flutningabíll'},
					{mynd: 'euro', svar: 'evra'},
];